# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/dfs.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'protos/dfs.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10protos/dfs.proto\"3\n\rUploadRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x10\n\x08\x66ilesize\x18\x02 \x01(\x03\"<\n\x0eUploadResponse\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x18\n\x10target_datanodes\x18\x02 \x03(\t\"+\n\tChunkData\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\")\n\x05Reply\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"+\n\nNodeStatus\x12\x0f\n\x07node_id\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\t2\x83\x01\n\nDFSService\x12\x30\n\rRequestUpload\x12\x0e.UploadRequest\x1a\x0f.UploadResponse\x12!\n\x0bUploadChunk\x12\n.ChunkData\x1a\x06.Reply\x12 \n\tHeartbeat\x12\x0b.NodeStatus\x1a\x06.Replyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.dfs_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_UPLOADREQUEST']._serialized_start=20
  _globals['_UPLOADREQUEST']._serialized_end=71
  _globals['_UPLOADRESPONSE']._serialized_start=73
  _globals['_UPLOADRESPONSE']._serialized_end=133
  _globals['_CHUNKDATA']._serialized_start=135
  _globals['_CHUNKDATA']._serialized_end=178
  _globals['_REPLY']._serialized_start=180
  _globals['_REPLY']._serialized_end=221
  _globals['_NODESTATUS']._serialized_start=223
  _globals['_NODESTATUS']._serialized_end=266
  _globals['_DFSSERVICE']._serialized_start=269
  _globals['_DFSSERVICE']._serialized_end=400
# @@protoc_insertion_point(module_scope)
